apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws9deploy
spec:
  strategy:
    type: Recreate
  replicas: 10
  selector:
    matchLabels:
      app: web        # (1) Pod 작성시 이 부분(labe -> app:web)이 포함되어야 함
  template:           # 여기에서부터 Pod 작성
    metadata:
      labels:
        app: web      # 반드시 (1)과 동일해야 함
    spec:
      containers:
        - name: aws9ctn
          image: songduckbae/aws9:green
---
apiVersion: v1
kind: Service
metadata:
  name: aws9-svc
spec:
  type: NodePort
  ports:
  - name: aws9-port 
    port: 8080        # clutserIP의 포트
    protocol: TCP
    targetPort: 80    # 컨테이너의 포트
    nodePort: 30080   # 노드의 포트
  selector:
    app: web